# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-12-10 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': [], 'permissions': (('user_add', '添加用户'), ('user_show', '查看用户'), ('user_update', '修改用户'), ('user_delete', '删除用户'))},
        ),
    ]
