# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-12-10 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0002_auto_20231210_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            options={
                'permissions': (('group_add', '添加用户组'), ('group_show', '查看用户组'), ('group_update', '修改用户组'), ('group_delete', '删除用户组')),
                'default_permissions': [],
            },
            bases=('auth.group',),
        ),
    ]
